services:
  aria2:
    image: adoyle/aria2:${IMAGE_VERSION:-1.1.0}
    container_name: aria2
    volumes:
      - ${DOWNLOAD_DIR:-./downloads}:/root/downloads
    ports:
      - ${WEB_PORT:-8080}:80
      - ${RPC_PORT:-6800}:6800
